### PR TITLE
Upgrade Nokogiri and Ruby versions

### PR DESCRIPTION
**Pull request by stanhu**

### CODE REVIEW

**Comment by stanhu** [comment]
@jorgemanrubia Could you take a look at this? Now that Nokogiri has released 1.10.0, this is the only gem that is blocking us from upgrading.

**Comment by jorgemanrubia** [comment]
Thanks. I will release a new version later today. Sorry I had missed this one!

**Comment by stanhu** [comment]
@jorgemanrubia Thanks! Just a friendly reminder.

**Comment by jorgemanrubia** [comment]
Version 0.7.11 released!

Thanks @stanhu!

**Pull request merged**
