### PR TITLE
Update nokogiri

### PR DESCRIPTION
**Pull request by josepjaume**
This updates nokogiri's dependency so it allows anything from `1.7.0` to `1.8.x` to be used.

### CODE REVIEW

**Comment by toupeira** [comment]
@jorgemanrubia any chance you could merge this? See [Nokogiri 1.8 CHANGELOG](https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.md#180--2017-06-04)

**Comment by toupeira** [comment]
Well that was quick, thanks 👍 

Also see https://github.com/jorgemanrubia/truncato/issues/18

**Comment by jorgemanrubia** [comment]
Sure thing! Sorry for the delay. I also released gem version 0.7.10 with this change

**Comment by toupeira** [comment]
@jorgemanrubia sweet, thanks! ❤️

**Pull request merged**
