### PR TITLE
Use a valid tag name for the artificial root element to avoid breaking behavior in latest Nokogiri

### PR DESCRIPTION
**Pull request by mattyoho**
Addresses https://github.com/jorgemanrubia/truncato/issues/20.

### CODE REVIEW

**Review by franzliedke — APPROVED** [review]
Excellent, thanks! 👏🏼

**Review by Dome-GER — APPROVED** [review]
Thanks for the fix!

**Comment by mateuszgorniak** [comment]
Thanks! Are there any plans to merge it and release soon?

**Comment by jorgemanrubia** [comment]
Released 0.7.12. Thanks folks 🙏

**Pull request merged**
